### ISSUE TITLE
message not displayed after sent

### ISSUE THREAD

**Issue by tjyang** [loco-rs/chat-rooms#2]
@kaplanelad 

Would you please fix this example to display test message after one entered "test msg" and hit Send button  ?

![image](https://github.com/loco-rs/chat-rooms/assets/378638/81089f50-0aef-417c-add1-0c08b02d42b3)

**Comment by kaplanelad** [comment]
it works for me:
![image](https://github.com/loco-rs/chat-rooms/assets/1224389/609e01be-badc-438a-b320-5904df1f041f)

can you give more details?

**Comment by tjyang** [comment]
- local src info.
```
[me@rocky9t01a chat-rooms]$ git log -1
commit 47c7442e11636ea46c3319c017d66a61e4150af3 (HEAD -> main, origin/main, origin/HEAD)
Merge: 6333787 827a3c3
Author: Elad Kaplan <kaplan.elad@gmail.com>
Date:   Sat Jan 20 23:05:08 2024 -0800

    Merge pull request #1 from locoabc/mytest

    view is not needed for now
[me@rocky9t01a chat-rooms]$ ip a |grep 192
    inet 192.168.241.128/24 brd 192.168.241.255 scope global dynamic noprefixroute ens160
[me@rocky9t01a chat-rooms]$
```
- run **cargo loco start** , startup log
```
[me@rocky9t01a chat-rooms]$ chat_rooms-cli start
2024-01-21T07:24:25.961853Z  INFO loco_rs::config: loading environment from selected_path="config/development.yaml"
2024-01-21T07:24:25.962637Z  INFO loco_rs::boot: initializers loaded initializers=""
2024-01-21T07:24:25.962942Z  INFO loco_rs::controller::app_routes: [Middleware] Adding limit payload data="5mb"
2024-01-21T07:24:25.962981Z  INFO loco_rs::controller::app_routes: [Middleware] Adding log trace id
2024-01-21T07:24:25.964506Z  INFO loco_rs::controller::app_routes: [Middleware] Adding static
2024-01-21T07:24:25.964597Z  INFO loco_rs::controller::app_routes: [Middleware] Adding etag layer
2024-01-21T07:24:25.964604Z  INFO loco_rs::controller::app_routes: [Middleware] Adding channels
<logo snipped>
                https://loco.rs

environment: development
     logger: debug
compilation: release
      modes: server

listening on port 3000
^C
[me@rocky9t01a chat-rooms]$ 
```
- Tested with two browser Chrome and MS Edge. 
   same problem on both that test message was not displayed after hitting Send button
  when Send button got clicked, console didn't show traffics

**Comment by tjyang** [comment]
- In frontend, Do I need to do a rebuild of some sort ?  I am using Rocky Linux 9 OS.
```
 /home/me/chat-rooms/frontend:
  total used in directory 292 available 82.9 GiB
  drwxr-xr-x 5 me me    201 Jan 20 20:39 .
  drwxr-xr-x 9 me me    195 Jan 21 01:29 ..
  drwxr-xr-x 3 me me     54 Jan 20 20:39 dist
  -rw-r--r-- 1 me me    355 Jan 20 20:39 index.html
  -rw-r--r-- 1 me me    892 Jan 20 20:39 package.json
  -rw-r--r-- 1 me me 170684 Jan 20 20:39 package-lock.json
  -rw-r--r-- 1 me me 103461 Jan 20 20:39 pnpm-lock.yaml
  -rw-r--r-- 1 me me     80 Jan 20 20:39 postcss.config.js
  drwxr-xr-x 2 me me     22 Jan 20 20:39 public
  drwxr-xr-x 5 me me     99 Jan 20 20:39 src
  -rw-r--r-- 1 me me    440 Jan 20 20:39 tailwind.config.js
  -rw-r--r-- 1 me me    163 Jan 20 20:39 vite.config.js

```

**Comment by kaplanelad** [comment]
no, don't need to install.

can you share the socket logs in the browser?

**Comment by tjyang** [comment]
- Chrome developer tools
![image](https://github.com/loco-rs/chat-rooms/assets/378638/cfb036b7-252f-411e-ade5-ea85a7feb171)

- expanded socket.io error details
![image](https://github.com/loco-rs/chat-rooms/assets/378638/9bacd7eb-69ea-4445-94bc-4a2c80ccaa8a)

- end

**Comment by kaplanelad** [comment]
did you run `cargo loco start` and browse the local app?

**Comment by tjyang** [comment]
> did you run `cargo loco start` and browse the local app?
Yes. 
![image](https://github.com/loco-rs/chat-rooms/assets/378638/57e71652-1aa8-4fca-b4e4-d6b93f9d9f2e)

- my debug effort per google search on socket.io connection's permission denied
```
[me@rocky9t01a frontend]$ host socket.io
socket.io has address 76.76.21.9
socket.io has address 76.76.21.241
[me@rocky9t01a frontend]$ sudo nmap -sP socket.io
Starting Nmap 7.92 ( https://nmap.org ) at 2024-01-21 06:11 CST
Nmap scan report for socket.io (76.76.21.61)
Host is up (0.00091s latency).
Other addresses for socket.io (not scanned): 76.76.21.98
Nmap done: 1 IP address (1 host up) scanned in 7.31 seconds
[me@rocky9t01a frontend]$

```

**Comment by kaplanelad** [comment]
From what I see, you browse to the website with `192.168.241.128:3000`, and the client creates a request to `localhost:3000`.

There is a reason why you are adding IP instead of localhost.

**Comment by tjyang** [comment]
> From what I see, you browse to the website with `192.168.241.128:3000`, and the client creates a request to `localhost:3000`.
> 
> There is a reason why you are adding IP instead of localhost.

rocky9t01a(192.168.241.128) running as VMWare workstation(hostname=P50) VM using NAT network. And then  P50(192.168.1.24) reach out to internet behind common home firewall/AP.

I will test out chat-room app on another 192.168.1.0/24 subnet to only go through one layer of NAT firewall.

**Comment by kaplanelad** [comment]
The frontend expects to open the socket to localhost. if you are changing it you need to change the socket URL [here](https://github.com/loco-rs/chat-rooms/blob/main/frontend/src/App.jsx#L29)  and rebuild the ui

**Comment by tjyang** [comment]
@kaplanelad 
Thanks for this pointer. I am able to see the chat message after sent, after I RDP into OS and browse http://localhost:3000. 
Hoping  this PR https://github.com/loco-rs/loco/pull/379 can help this confusing issue download the road.
I will rebuild the frontend for now.

**Comment by kaplanelad** [comment]
np, enjoy your new chat room discusses :)
